### PR TITLE
feat: Typst Code syntax definition

### PR DESCRIPTION
**Pull request by istudyatuni**
See https://github.com/sublimelsp/LSP/issues/2472

image

### CODE REVIEW

**Review by hyrious — APPROVED** [review]

**Comment by istudyatuni** [comment]
One problem - in dictionaries nothing is highlighted

<details><summary>comparison</summary>
<p>

image
image


</p>
</details>

**Comment by hyrious** [comment]
@istudyatuni Yep, the problem here is the inspected output:

```typc
[( foo(bar: 42) )]
```

…is considered a content-block `[]` which are literal texts.

It seems the `#repr()` representation's syntax is a little different with the one in script block `#{}`. Is there any specifications or implement details of that?

Maybe we just have to add some special cases in this syntax file.

**Comment by istudyatuni** [comment]
Yes, it differs, there was a PR to fix it, but it abandoned for a while. Probably TypstCode should always start code, e.g. when see opening brackets

**Comment by istudyatuni** [comment]
Yes, it differs, there was a PR to fix it, but it abandoned for a while. Probably TypstCode should always start code, e.g. when see opening brackets

**Comment by hyrious** [comment]
I found something interesting and it now works although I don't know why -- https://github.com/hyrious/typst-syntax-highlight/commit/45627af5953ad7c0e857af5d2d6fd58f4119674e

image

**Comment by istudyatuni** [comment]
Cool, thanks!

**Comment by istudyatuni** [comment]
So basically it could be just

```yaml
contexts:
  main:
    - include: script-common
```

**Comment by hyrious** [comment]
@istudyatuni It couldn't. In fact this following code works too:

```yaml
contexts:
  main:
    - include: script-common
  scripts: # you can't delete this
    - include: script-common
```

I guess this is because the `scripts` section is also defined in the original syntax file. By re-defining `scripts`, it slightly changes the syntax.

**Pull request merged**
